"""add_incident_resolved_fields

Revision ID: 95dccafb1304
Revises: 7a4c202a07ed
Create Date: 2026-06-03 16:02:02.959308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95dccafb1304'
down_revision: Union[str, Sequence[str], None] = '7a4c202a07ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incidents', sa.Column('resolved', sa.Boolean(), nullable=False))
    op.add_column('incidents', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('incidents', 'resolved_at')
    op.drop_column('incidents', 'resolved')
    # ### end Alembic commands ###
