"""Baseline schema (squash of initial_schema + incident fields + p0 constraints)

Revision ID: c7d8e9f00123
Revises: 
Create Date: 2026-07-08 00:24:29.382352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d8e9f00123'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_tools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tool_type', sa.String(length=64), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('free_observation', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=128), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_target', 'audit_logs', ['target_type', 'target_id'], unique=False)
    op.create_index('ix_audit_logs_user_action', 'audit_logs', ['user_email', 'action'], unique=False)
    op.create_table('ecoe_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('course_name', sa.String(length=255), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('responsible_teacher', sa.String(length=255), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=False),
    sa.Column('circuit_mode', sa.String(length=64), nullable=False),
    sa.Column('total_stations', sa.Integer(), nullable=False),
    sa.Column('station_time_minutes', sa.Float(), nullable=False),
    sa.Column('transition_time_minutes', sa.Float(), nullable=False),
    sa.Column('total_students', sa.Integer(), nullable=False),
    sa.Column('total_groups', sa.Integer(), nullable=False),
    sa.Column('passing_reference_percent', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('timer_sound_asset_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # FK to media_assets added at the end of upgrade() — circular dependency
    # ecoe_events -> media_assets -> stations -> ecoe_events
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ecoe_events_status_date', 'ecoe_events', ['status', 'date'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('target_viewer', sa.String(length=64), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # FK to stations added at the end of upgrade() — circular dependency
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_media_assets_station_viewer', 'media_assets', ['station_id', 'target_viewer'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('simulated_patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_name', sa.String(length=255), nullable=False),
    sa.Column('summary_profile', sa.Text(), nullable=False),
    sa.Column('base_story', sa.Text(), nullable=False),
    sa.Column('key_answers', sa.Text(), nullable=False),
    sa.Column('emotional_tone', sa.String(length=255), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('default_configuration', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('assessment_tool_id', sa.Integer(), nullable=True),
    sa.Column('simulated_patient_id', sa.Integer(), nullable=True),
    sa.Column('station_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('station_type', sa.String(length=64), nullable=False),
    sa.Column('circuit_name', sa.String(length=64), nullable=False),
    sa.Column('station_time_minutes', sa.Float(), nullable=False),
    sa.Column('transition_time_minutes', sa.Float(), nullable=False),
    sa.Column('expected_outcomes', sa.Text(), nullable=False),
    sa.Column('student_activity', sa.Text(), nullable=False),
    sa.Column('student_station_instruction', sa.Text(), nullable=False),
    sa.Column('pre_entry_instruction', sa.Text(), nullable=False),
    sa.Column('evaluator_instruction', sa.Text(), nullable=False),
    sa.Column('requires_evaluator', sa.Boolean(), nullable=False),
    sa.Column('requires_student_form', sa.Boolean(), nullable=False),
    sa.Column('uses_multimedia', sa.Boolean(), nullable=False),
    sa.Column('uses_simulated_patient', sa.Boolean(), nullable=False),
    sa.Column('uses_physical_resources', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('materials', sa.Text(), nullable=False),
    sa.Column('clinical_equipment', sa.Text(), nullable=False),
    sa.Column('simulator', sa.Text(), nullable=False),
    sa.Column('ambience', sa.Text(), nullable=False),
    sa.Column('multimedia_notes', sa.Text(), nullable=False),
    sa.Column('student_form_definition', sa.JSON(), nullable=False),
    sa.Column('contingency_ready', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_tool_id'], ['assessment_tools.id'], ),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['simulated_patient_id'], ['simulated_patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['station_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'station_number', name='uq_station_event_number')
    )
    op.create_index('ix_stations_event_circuit', 'stations', ['ecoe_event_id', 'circuit_name'], unique=False)
    op.create_index('ix_stations_event_status', 'stations', ['ecoe_event_id', 'status'], unique=False)
    op.create_table('assessment_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('score_per_item', sa.Float(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['assessment_tools.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_id', 'order_index', name='uq_assessment_item_tool_order')
    )
    op.create_index('ix_assessment_items_tool', 'assessment_items', ['tool_id'], unique=False)
    op.create_table('circuits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('is_mirror', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'name', name='uq_circuit_event_name')
    )
    op.create_index('ix_circuits_event', 'circuits', ['ecoe_event_id'], unique=False)
    op.create_table('contingency_exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('export_type', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_contingency_exports_event_type', 'contingency_exports', ['ecoe_event_id', 'export_type'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_incidents_event_resolved', 'incidents', ['ecoe_event_id', 'resolved'], unique=False)
    op.create_index('ix_incidents_event_station', 'incidents', ['ecoe_event_id', 'station_id'], unique=False)
    op.create_table('live_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('station_time_seconds', sa.Integer(), nullable=False),
    sa.Column('transition_time_seconds', sa.Integer(), nullable=False),
    sa.Column('current_station_index', sa.Integer(), nullable=False),
    sa.Column('remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', name='uq_live_session_event')
    )
    op.create_index('ix_live_sessions_event_status', 'live_sessions', ['ecoe_event_id', 'status'], unique=False)
    op.create_table('pilot_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.String(length=64), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pilot_runs_event_archived', 'pilot_runs', ['ecoe_event_id', 'archived'], unique=False)
    op.create_table('staff_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.Column('station_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'email', name='uq_staff_event_email')
    )
    op.create_index('ix_staff_event_role', 'staff_assignments', ['ecoe_event_id', 'role_code'], unique=False)
    op.create_table('station_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('assessment_tool_id', sa.Integer(), nullable=True),
    sa.Column('simulated_patient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('station_type', sa.String(length=64), nullable=False),
    sa.Column('circuit_name', sa.String(length=64), nullable=False),
    sa.Column('expected_outcomes', sa.Text(), nullable=False),
    sa.Column('student_activity', sa.Text(), nullable=False),
    sa.Column('student_station_instruction', sa.Text(), nullable=False),
    sa.Column('pre_entry_instruction', sa.Text(), nullable=False),
    sa.Column('evaluator_instruction', sa.Text(), nullable=False),
    sa.Column('requires_evaluator', sa.Boolean(), nullable=False),
    sa.Column('requires_student_form', sa.Boolean(), nullable=False),
    sa.Column('uses_multimedia', sa.Boolean(), nullable=False),
    sa.Column('uses_simulated_patient', sa.Boolean(), nullable=False),
    sa.Column('uses_physical_resources', sa.Boolean(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('materials', sa.Text(), nullable=False),
    sa.Column('clinical_equipment', sa.Text(), nullable=False),
    sa.Column('simulator', sa.Text(), nullable=False),
    sa.Column('ambience', sa.Text(), nullable=False),
    sa.Column('multimedia_notes', sa.Text(), nullable=False),
    sa.Column('student_form_definition', sa.JSON(), nullable=False),
    sa.Column('contingency_ready', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_tool_id'], ['assessment_tools.id'], ),
    sa.ForeignKeyConstraint(['simulated_patient_id'], ['simulated_patients.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['station_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_resources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_station_resources_station', 'station_resources', ['station_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('rut', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ecoe_number', sa.String(length=32), nullable=False),
    sa.Column('group_name', sa.String(length=64), nullable=False),
    sa.Column('circuit_name', sa.String(length=64), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'ecoe_number', name='uq_student_event_ecoe_number'),
    sa.UniqueConstraint('ecoe_event_id', 'rut', name='uq_student_event_rut')
    )
    op.create_index('ix_students_event_active', 'students', ['ecoe_event_id', 'is_active'], unique=False)
    op.create_index('ix_students_event_email', 'students', ['ecoe_event_id', 'email'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ecoe_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'user_id', 'role_code', name='uq_ecoe_permission_event_user_role')
    )
    op.create_index('ix_ecoe_permissions_event_user', 'ecoe_permissions', ['ecoe_event_id', 'user_id'], unique=False)
    op.create_table('ecoe_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('equivalent_grade', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'student_id', name='uq_ecoe_result_event_student')
    )
    op.create_index('ix_ecoe_results_event', 'ecoe_results', ['ecoe_event_id'], unique=False)
    op.create_table('evaluator_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('live_session_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('score_obtained', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('observation', sa.Text(), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('by_contingency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'station_id', 'student_id', 'mode', name='uq_evaluator_record_event_station_student_mode')
    )
    op.create_index('ix_evaluator_records_event_station', 'evaluator_records', ['ecoe_event_id', 'station_id'], unique=False)
    op.create_index('ix_evaluator_records_event_student', 'evaluator_records', ['ecoe_event_id', 'student_id'], unique=False)
    op.create_table('pilot_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pilot_run_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pilot_run_id'], ['pilot_runs.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pilot_run_id', 'station_id', name='uq_pilot_record_run_station')
    )
    op.create_index('ix_pilot_records_station', 'pilot_records', ['station_id'], unique=False)
    op.create_table('station_checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('evaluator_email', sa.String(length=255), nullable=False),
    sa.Column('evaluator_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_station_checkins_event_station_status', 'station_checkins', ['ecoe_event_id', 'station_id', 'status'], unique=False)
    op.create_index('ix_station_checkins_event_student_status', 'station_checkins', ['ecoe_event_id', 'student_id', 'status'], unique=False)
    op.create_table('station_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('obtained_score', sa.Float(), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=False),
    sa.Column('percent_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'station_id', 'student_id', name='uq_station_result_event_station_student')
    )
    op.create_index('ix_station_results_event_student', 'station_results', ['ecoe_event_id', 'student_id'], unique=False)
    op.create_table('student_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuits.id'], ),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'name', name='uq_student_group_event_name')
    )
    op.create_index('ix_student_groups_event', 'student_groups', ['ecoe_event_id'], unique=False)
    op.create_table('student_responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ecoe_event_id', sa.Integer(), nullable=False),
    sa.Column('live_session_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('answers', sa.JSON(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('by_contingency', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ecoe_event_id'], ['ecoe_events.id'], ),
    sa.ForeignKeyConstraint(['live_session_id'], ['live_sessions.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ecoe_event_id', 'station_id', 'student_id', 'mode', name='uq_student_response_event_station_student_mode')
    )
    op.create_index('ix_student_responses_event_station', 'student_responses', ['ecoe_event_id', 'station_id'], unique=False)
    op.create_index('ix_student_responses_event_student', 'student_responses', ['ecoe_event_id', 'student_id'], unique=False)

    # Deferred FKs that close the circular dependency between
    # ecoe_events, media_assets and stations.
    if op.get_bind().dialect.name == 'sqlite':
        # SQLite cannot ALTER a table to add constraints. Batch mode rebuilds
        # each table after all three circularly-related tables already exist.
        with op.batch_alter_table('ecoe_events') as batch_op:
            batch_op.create_foreign_key(
                'ecoe_events_timer_sound_asset_id_fkey',
                'media_assets', ['timer_sound_asset_id'], ['id'],
            )
        with op.batch_alter_table('media_assets') as batch_op:
            batch_op.create_foreign_key(
                'media_assets_station_id_fkey',
                'stations', ['station_id'], ['id'],
            )
    else:
        op.create_foreign_key(
            'ecoe_events_timer_sound_asset_id_fkey',
            'ecoe_events', 'media_assets',
            ['timer_sound_asset_id'], ['id'],
        )
        op.create_foreign_key(
            'media_assets_station_id_fkey',
            'media_assets', 'stations',
            ['station_id'], ['id'],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Drop the deferred FKs first so tables can be dropped in any order.
    if op.get_bind().dialect.name == 'sqlite':
        with op.batch_alter_table('media_assets') as batch_op:
            batch_op.drop_constraint('media_assets_station_id_fkey', type_='foreignkey')
        with op.batch_alter_table('ecoe_events') as batch_op:
            batch_op.drop_constraint('ecoe_events_timer_sound_asset_id_fkey', type_='foreignkey')
    else:
        op.drop_constraint('media_assets_station_id_fkey', 'media_assets', type_='foreignkey')
        op.drop_constraint('ecoe_events_timer_sound_asset_id_fkey', 'ecoe_events', type_='foreignkey')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_responses_event_student', table_name='student_responses')
    op.drop_index('ix_student_responses_event_station', table_name='student_responses')
    op.drop_table('student_responses')
    op.drop_index('ix_student_groups_event', table_name='student_groups')
    op.drop_table('student_groups')
    op.drop_index('ix_station_results_event_student', table_name='station_results')
    op.drop_table('station_results')
    op.drop_index('ix_station_checkins_event_student_status', table_name='station_checkins')
    op.drop_index('ix_station_checkins_event_station_status', table_name='station_checkins')
    op.drop_table('station_checkins')
    op.drop_index('ix_pilot_records_station', table_name='pilot_records')
    op.drop_table('pilot_records')
    op.drop_index('ix_evaluator_records_event_student', table_name='evaluator_records')
    op.drop_index('ix_evaluator_records_event_station', table_name='evaluator_records')
    op.drop_table('evaluator_records')
    op.drop_index('ix_ecoe_results_event', table_name='ecoe_results')
    op.drop_table('ecoe_results')
    op.drop_index('ix_ecoe_permissions_event_user', table_name='ecoe_permissions')
    op.drop_table('ecoe_permissions')
    op.drop_table('users')
    op.drop_index('ix_students_event_email', table_name='students')
    op.drop_index('ix_students_event_active', table_name='students')
    op.drop_table('students')
    op.drop_index('ix_station_resources_station', table_name='station_resources')
    op.drop_table('station_resources')
    op.drop_table('station_bank')
    op.drop_index('ix_staff_event_role', table_name='staff_assignments')
    op.drop_table('staff_assignments')
    op.drop_index('ix_pilot_runs_event_archived', table_name='pilot_runs')
    op.drop_table('pilot_runs')
    op.drop_index('ix_live_sessions_event_status', table_name='live_sessions')
    op.drop_table('live_sessions')
    op.drop_index('ix_incidents_event_station', table_name='incidents')
    op.drop_index('ix_incidents_event_resolved', table_name='incidents')
    op.drop_table('incidents')
    op.drop_index('ix_contingency_exports_event_type', table_name='contingency_exports')
    op.drop_table('contingency_exports')
    op.drop_index('ix_circuits_event', table_name='circuits')
    op.drop_table('circuits')
    op.drop_index('ix_assessment_items_tool', table_name='assessment_items')
    op.drop_table('assessment_items')
    op.drop_index('ix_stations_event_status', table_name='stations')
    op.drop_index('ix_stations_event_circuit', table_name='stations')
    op.drop_table('stations')
    op.drop_table('station_templates')
    op.drop_table('simulated_patients')
    op.drop_table('roles')
    op.drop_index('ix_media_assets_station_viewer', table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index('ix_ecoe_events_status_date', table_name='ecoe_events')
    op.drop_table('ecoe_events')
    op.drop_index('ix_audit_logs_user_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_target', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('assessment_tools')
    # ### end Alembic commands ###
