server {
    listen 80;
    listen [::]:80;
    server_name ecoe.cl www.ecoe.cl;
    return 301 https://ecoe.cl$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name www.ecoe.cl;

    ssl_certificate /etc/letsencrypt/live/ecoe.cl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ecoe.cl/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    return 301 https://ecoe.cl$request_uri;
}

server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name ecoe.cl;

    ssl_certificate /etc/letsencrypt/live/ecoe.cl/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ecoe.cl/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/ecoe-cl;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
